### ISSUE TITLE
Logo/Icon Proposal

### ISSUE THREAD

**Issue by jbeguna04** [behei/etabot-ui#9]
Hi good day! Im Jibbie Eguna, a graphics designer, I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by behei** [comment]
Hello @jbeguna04! Sure, I'd love to see you contribute to this open-source project!

**Comment by jbeguna04** [comment]
Thank you, allow me to post my design her. Ill try to comment the designs here later

**Comment by jbeguna04** [comment]
![etabot-ui](https://user-images.githubusercontent.com/35353768/40121542-63c74de0-5954-11e8-90f7-ef151530503f.png)
